version: "3"

services:
  postgis:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD?PGPASSWORD is unset}
    container_name: postgis
    restart: unless-stopped
    volumes:
      - "postgis_data_vol:/var/lib/postgresql/data"
      - "/var/scratch:/var/scratch"
    ports:
      - "5432:5432"

volumes:
  postgis_data_vol:
